#!/bin/bash

echo "Initialisation du reseau"
iwconfig wlan0 mode ad-hoc channel 1 essid MyAdhoc key 1234567890 ap 02:12:34:56:78:90

echo "Demarage de wlan0"
ifconfig wlan0 mtu 1528
batctl if add wlan0
ifconfig wlan0 up
ifconfig bat0 up
ifconfig wlan0 192.168.0.100/24 netmask 255.255.255.0
ifconfig bat0 192.168.1.100/24 netmask 255.255.255.0

